	  <!-- path to avatar -->         <!-- avatar name -->
	  <option value="../imagens/avatars/abstract.jpg">Abstrato</option> 
	    <option value="../imagens/avatars/alien_helmet.jpg">Alien Helmet</option> 
	    <option value="../imagens/avatars/anglewings.jpg">Anglewings</option>
	    <option value="../imagens/avatars/axe.jpg">Axe</option>
	    <option value="../imagens/avatars/basket.jpg">Basket</option>
	    <option value="../imagens/avatars/bass_fret.jpg">Bass</option>
	    <option value="../imagens/avatars/animal_bear.jpg">Bear</option>
	    <option value="../imagens/avatars/animal_bird.jpg">Bird</option>
	    <option value="../imagens/avatars/hiro_bird2.jpg">Bird II</option>
	    <option value="../imagens/avatars/hiro_bird2_neg.jpg">Bird II Negative</option>
	    <option value="../imagens/avatars/hiro_bird.jpg">Bird III</option>
	    <option value="../imagens/avatars/character_bonehead.jpg">Bonehead</option>
	    <option value="../imagens/avatars/box_avatar.gif">Box Avatar</option>
	    <option value="../imagens/avatars/animal_butterfly.jpg">Butterfly I</option>
	    <option value="../imagens/avatars/butterfly2.jpg">Butterfly II</option>
	    <option value="../imagens/avatars/butterfly3.jpg">Butterfly III</option>
	    <option value="../imagens/avatars/animal_butterfly_neg.jpg">Butterfly Negative</option>
	    <option value="../imagens/avatars/candle.jpg">Candle</option>
	    <option value="../imagens/avatars/character_catafly.jpg">Catafly</option>
	    <option value="../imagens/avatars/center.jpg">Center</option>
	    <option value="../imagens/avatars/chi.gif">Chi</option>
	    <option value="../imagens/avatars/character_cyclops.jpg">Cyclops</option>
	    <option value="../imagens/avatars/darksword.jpg">Dark Sword</option>
	    <option value="../imagens/avatars/dragon_eye.jpg">Dragon Eye</option>
	    <option value="../imagens/avatars/animal_doggy.jpg">Doggy</option>
	    <option value="../imagens/avatars/animal_doggy2.jpg">Doggy II</option>
	    <option value="../imagens/avatars/hiro_dolphin.jpg">Dolphin</option>
	    <option value="../imagens/avatars/hiro_dolphin_neg.jpg">Dolphin Negative</option>
	    <option value="../imagens/avatars/animal_duck.jpg">Duck</option>
	    <option value="../imagens/avatars/animal_eel.jpg">Eel</option>
	    <option value="../imagens/avatars/eye.jpg">Eye</option>
	    <option value="../imagens/avatars/eye2.jpg">Eye II</option>
	    <option value="../imagens/avatars/eye_storm.jpg">Eye Storm</option>
	    <option value="../imagens/avatars/flower.jpg">Flower</option>
	    <option value="../imagens/avatars/flower2.jpg">Flower II</option>
	    <option value="../imagens/avatars/flying.jpg">Flying</option>
	    <option value="../imagens/avatars/funkyfish.jpg">Funky Fish</option>
	    <option value="../imagens/avatars/hiro_giraff.jpg">Giraff</option>
	    <option value="../imagens/avatars/hiro_giraff_neg.jpg">Giraff Negative</option>
	    <option value="../imagens/avatars/gorilla_skull.jpg">Gorilla Skull</option>
	    <option value="../imagens/avatars/half_planet.jpg">Half Planet</option>
	    <option value="../imagens/avatars/hiro_horse.jpg">Horse</option>
	    <option value="../imagens/avatars/hiro_horse_neg.jpg">Horse Negative</option>
	    <option value="../imagens/avatars/hand_neg.jpg">Hand Negative</option>
	    <option value="../imagens/avatars/kanji_for_peace.jpg">Kanji For Peace</option>
	    <option value="../imagens/avatars/leaf.jpg">Leaf</option>
	    <option value="../imagens/avatars/lightbulb.jpg">Lightbulb</option>
	    <option value="../imagens/avatars/lightening.jpg">Lightening</option>
	    <option value="../imagens/avatars/lighthouse.jpg">Lighthouse</option>
	    <option value="../imagens/avatars/animal_lizard.jpg">Lizard</option>
	    <option value="../imagens/avatars/mask.jpg">Mask</option>
	    <option value="../imagens/avatars/metalbird.jpg">Metalbird</option>
	    <option value="../imagens/avatars/animal_monkey.jpg">Monkey</option>
	    <option value="../imagens/avatars/animal_monkey2.jpg">Monkey II</option>
	    <option value="../imagens/avatars/moon.jpg">Moon</option>
	    <option value="../imagens/avatars/octa_feathers.jpg">Octa Feathers</option>
	    <option value="../imagens/avatars/aninal_peac.jpg">Peacock</option>
	    <option value="../imagens/avatars/character_pinprick.jpg">Pinprick</option>
	    <option value="../imagens/avatars/praying_hands.jpg">Praying Hands</option>
	    <option value="../imagens/avatars/pyramid.jpg">Pyramid</option>
	    <option value="../imagens/avatars/radar.jpg">Radar</option>
	    <option value="../imagens/avatars/redcross.jpg">Redcross</option>
	    <option value="../imagens/avatars/rocking_horse.jpg">Rocking Horse</option>
	    <option value="../imagens/avatars/scifi_planet_probe.jpg">Scifi Planet Probe</option>
	    <option value="../imagens/avatars/seabug1.jpg">Sea Bug</option>
	    <option value="../imagens/avatars/seecreature.jpg">Sea Creature</option>
	    <option value="../imagens/avatars/seahorse_animation.gif">Seahorse Animation</option>
	    <option value="../imagens/avatars/animal_shark.jpg">Shark</option>
	    <option value="../imagens/avatars/shape_barbed.jpg">Shape Barbed</option>
	    <option value="../imagens/avatars/shapes_quad_feather.jpg">Shapes Quad Feather</option>
	    <option value="../imagens/avatars/side_smile.jpg">Side Smile</option>
	    <option value="../imagens/avatars/side_smile_b.jpg">Side Smile II</option>
	    <option value="../imagens/avatars/character_space_monkey.jpg">Space Monkey</option>
	    <option value="../imagens/avatars/Sphere_animated2.gif">Sphere Animated</option>
	    <option value="../imagens/avatars/Sphere_animated_small_ neg2.gif">Sphere Animated II</option>
	    <option value="../imagens/avatars/spherewall.gif">Sphere Wall</option>
	    <option value="../imagens/avatars/spider.jpg">Spider</option>
	    <option value="../imagens/avatars/stone_face.jpg">Stone Face</option>
	    <option value="../imagens/avatars/stone_fish.jpg">Stone Fish</option>
	    <option value="../imagens/avatars/scene_sunoverlake.jpg">Sun over Lake</option>
	    <option value="../imagens/avatars/scene_sunovermountains.jpg">Sun over Mountains</option>
	    <option value="../imagens/avatars/animal_swan.jpg">Swan</option>
	    <option value="../imagens/avatars/shapes_swish.jpg">Swish</option>
	    <option value="../imagens/avatars/shapes_taran.jpg">Taran</option>
	    <option value="../imagens/avatars/techno_eye.jpg">Techno Eye</option>
	    <option value="../imagens/avatars/animal_vultar.jpg">Vultar</option>
	    <option value="../imagens/avatars/character_warrior.jpg">Warrior</option>
	    <option value="../imagens/avatars/scenery_water_mountains.jpg">Water Mountains</option>
	    <option value="../imagens/avatars/waveform.jpg">Waveform</option>
	    <option value="../imagens/avatars/web.jpg">Web</option>
	    <option value="../imagens/avatars/animal_whale.jpg">Whale</option>
	    <option value="../imagens/avatars/white_face.jpg">White Face</option>
	    <option value="../imagens/avatars/WINGS.jpg">Wings</option>
	    <option value="../imagens/avatars/wings2.jpg">Wings II</option>
	    <option value="../imagens/avatars/wired_shell.jpg">Wired Shell</option>
	  	<option >----- Avatars Escalada ------</option>
	    <option value="../imagens/avatars/1_copam_av_1.jpg">Marumbi 1</option>
		<option value="../imagens/avatars/1_copam_av_2.jpg">Marumbi 2</option> 
		<option value="../imagens/avatars/1_copam_av_3.jpg">S.L.Purunã (Setor 3)</option> 
		<option value="../imagens/avatars/1_copam_av_4.jpg">Anhãngava 1</option> 
		<option value="../imagens/avatars/1_copam_av_5.jpg">Anhângava 2</option>
		<option value="../imagens/avatars/1_copam_av_7.jpg">Anhângava 3</option>  
		<option value="../imagens/avatars/1_copam_av_27.jpg">Campo Escola de Toledo 1</option> 
		
		<option value="../imagens/avatars/1_copam_av_8.jpg">Escalada 1</option> 
		<option value="../imagens/avatars/1_copam_av_9.jpg">Escalada 2</option> 
		<option value="../imagens/avatars/1_copam_av_10.jpg">Escalada 3</option> 
		<option value="../imagens/avatars/1_copam_av_11.jpg">Escalada 4</option> 
		<option value="../imagens/avatars/1_copam_av_12.jpg">Escalada 5</option> 
		<option value="../imagens/avatars/1_copam_av_13.jpg">Escalada 6</option> 
		<option value="../imagens/avatars/1_copam_av_14.jpg">Escalada 7</option> 
		<option value="../imagens/avatars/1_copam_av_6.jpg">Escalada 8</option> 
		<option value="../imagens/avatars/1_copam_av_15.jpg">Friend de Cara</option> 
		
		<option value="../imagens/avatars/1_copam_av_17.jpg">Nuts usado</option> 
		<option value="../imagens/avatars/1_copam_av_18.jpg">Corda usada</option> 
		<option value="../imagens/avatars/1_copam_av_19.jpg">Piton Velho</option> 
		<option value="../imagens/avatars/1_copam_av_20.jpg">Búsula</option> 
		<option value="../imagens/avatars/1_copam_av_21.jpg">Mapa</option> 
		<option value="../imagens/avatars/1_copam_av_22.jpg">CooperHead Velho</option> 
		<option value="../imagens/avatars/1_copam_av_23.jpg">Oito Velho</option> 
		<option value="../imagens/avatars/1_copam_av_24.jpg">Panela Velha</option> 
		<option value="../imagens/avatars/1_copam_av_25.jpg">Stopprs Usados</option> 
		<option value="../imagens/avatars/1_copam_av_26.jpg">Tênis Velho</option>
		
		<option value="../imagens/avatars/1_copam_av_28.jpg">Mosquetão Velho</option> 
		<option value="../imagens/avatars/1_copam_av_29.jpg">ATC</option> 
		<option value="../imagens/avatars/1_copam_av_30.jpg">Jogo de Peças</option> 
		<option value="../imagens/avatars/1_copam_av_31.jpg">Costura Expressa</option> 
		<option value="../imagens/avatars/1_copam_av_32.jpg">Fifi</option> 
		<option value="../imagens/avatars/1_copam_av_33.jpg">Corda</option> 
		<option value="../imagens/avatars/1_copam_av_34.jpg">Gri-Gri</option> 
		<option value="../imagens/avatars/1_copam_av_35.jpg">Sapatilha</option> 
		<option value="../imagens/avatars/1_copam_av_36.jpg">Chapeleta</option> 
		<option value="../imagens/avatars/1_copam_av_37.jpg">Ascender</option> 
		<option value="../imagens/avatars/1_copam_av_38.jpg">Camelots</option> 
		<option value="../imagens/avatars/1_copam_av_39.jpg">Pino "P"</option> 
		<option value="../imagens/avatars/1_copam_av_40.jpg">Mosquetão sem rosca</option> 
		<option value="../imagens/avatars/1_copam_av_41.jpg">Mosquetão Oval com rosca</option>
		<option value="../imagens/avatars/1_copam_av_43.jpg">Mosquetão Pêra</option>  
		<option value="../imagens/avatars/1_copam_av_42.jpg">Capacete</option> 
		
		<option value="../imagens/avatars/1_copam_av_44.jpg">Bivaque</option> 
		<option value="../imagens/avatars/1_copam_av_45.jpg">Micro Nuts</option>
	
		